export const CREATE_TODO_LIST = 'CREATE_TODO_LIST';
export const FETCH_TODO_LISTS  = 'FETCH_TODO_LISTS';
export const DELETE_TODO_LIST  = 'DELETE_TODO_LIST';
export const UPDATE_IS_COMPLETED_FLAG = 'UPDATE_IS_COMPLETED_FLAG'



